apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: mender-redis
  name: mender-redis
spec:
  containers:
  - image: redis:3.2.11-alpine
    name: mender-redis
    resources: {}
  restartPolicy: OnFailure
status: {}
