apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: mender-gui
  name: mender-gui
spec:
  containers:
  - env:
    - name: INTEGRATION_VERSION
    image: mendersoftware/gui:master
    name: mender-gui
    resources: {}
  restartPolicy: OnFailure
status: {}
