apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: mender-mongo
  name: mender-mongo
spec:
  containers:
  - image: mongo:3.4
    name: mender-mongo
    resources: {}
  restartPolicy: OnFailure
status: {}
