apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: mender-elasticsearch
  name: mender-elasticsearch
spec:
  containers:
  - image: mendersoftware/elasticsearch:2.4
    name: mender-elasticsearch
    resources: {}
  restartPolicy: OnFailure
status: {}
