apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: mender-device-auth
  name: mender-device-auth
spec:
  containers:
  - image: mendersoftware/deviceauth:master
    name: mender-device-auth
    resources: {}
  restartPolicy: OnFailure
status: {}
